# Generated by Django 4.2 on 2023-08-21 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('bookname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.books_list')),
            ],
        ),
    ]
