# Generated by Django 4.2 on 2023-08-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_member_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_list',
            name='borrowdate',
            field=models.DateField(auto_now=True),
        ),
    ]
