# Generated by Django 4.2 on 2023-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0003_member_list_borrowdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_list',
            name='borrowedon',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member_list',
            name='borrowdate',
            field=models.DateField(),
        ),
    ]
